<?php

use App\Http\Controllers\Api\AdminDashboardController;
use App\Http\Controllers\Api\AdminPlanLimitController;
use App\Http\Controllers\Api\AppleCalendarController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BillingController;
use App\Http\Controllers\Api\CouponCodeController;
use App\Http\Controllers\Api\DashboardChangeController;
use App\Http\Controllers\Api\DomainResourceController;
use App\Http\Controllers\Api\ExternalCalendarController;
use App\Http\Controllers\Api\GoogleCalendarController;
use App\Http\Controllers\Api\IssueReportController;
use App\Http\Controllers\Api\OutlookCalendarController;
use App\Http\Controllers\Api\PlaceController;
use App\Http\Controllers\Api\PushNotificationDeviceTokenController;
use App\Http\Controllers\Api\TodaySummaryController;
use App\Http\Controllers\Api\WorkspaceController;
use Illuminate\Support\Facades\Route;

Route::middleware('api.rate_limit')->group(function (): void {
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/email-availability', [AuthController::class, 'emailAvailability']);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::get('/google-calendar/callback', [GoogleCalendarController::class, 'callback']);
    Route::get('/outlook-calendar/callback', [OutlookCalendarController::class, 'callback']);
    Route::post('/billing/stripe/webhook', [BillingController::class, 'webhook']);

    Route::middleware('auth.bearer')->group(function (): void {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::patch('/auth/me', [AuthController::class, 'update']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::delete('/account', [AuthController::class, 'destroy']);
        Route::get('/account/export', [AuthController::class, 'export']);
        Route::get('/billing/subscription', [BillingController::class, 'show']);
        Route::post('/billing/mobile-subscriptions/setup', [BillingController::class, 'mobileSubscriptionSetup']);
        Route::post('/billing/mobile-subscriptions/confirm', [BillingController::class, 'confirmMobileSubscription']);
        Route::get('/billing/payment-method', [BillingController::class, 'paymentMethod']);
        Route::post('/billing/payment-method/setup', [BillingController::class, 'paymentMethodSetup']);
        Route::post('/billing/payment-method/checkout-session', [BillingController::class, 'paymentMethodCheckoutSession']);
        Route::post('/billing/payment-method/confirm', [BillingController::class, 'confirmPaymentMethod']);
        Route::post('/billing/checkout-sessions', [BillingController::class, 'checkoutSession']);
        Route::post('/billing/subscription/upgrade', [BillingController::class, 'upgrade']);
        Route::post('/billing/subscription/change-plan', [BillingController::class, 'changePlan']);
        Route::post('/billing/subscription/cancel', [BillingController::class, 'cancel']);
        Route::post('/billing/subscription/resume', [BillingController::class, 'resume']);
        Route::post('/billing/coupon-codes/redeem', [CouponCodeController::class, 'redeem']);

        Route::get('/workspaces', [WorkspaceController::class, 'index']);
        Route::post('/workspaces', [WorkspaceController::class, 'store']);
        Route::patch('/workspaces/default', [WorkspaceController::class, 'setDefault']);
        Route::get('/workspaces/{workspace}', [WorkspaceController::class, 'show']);
        Route::patch('/workspaces/{workspace}', [WorkspaceController::class, 'update']);
        Route::post('/workspaces/{workspace}/invitations', [WorkspaceController::class, 'invite']);
        Route::post('/workspace-invitations/{token}/accept', [WorkspaceController::class, 'accept']);
        Route::patch('/workspaces/{workspace}/members/{member}', [WorkspaceController::class, 'updateMember']);
        Route::delete('/workspaces/{workspace}/members/{member}', [WorkspaceController::class, 'destroyMember']);
        Route::post('/workspaces/{workspace}/leave', [WorkspaceController::class, 'leave']);
        Route::post('/workspaces/{source}/sync-all', [WorkspaceController::class, 'syncAll']);
        Route::patch('/workspaces/{workspace}/google-calendars', [WorkspaceController::class, 'calendars']);

        Route::get('/today', [TodaySummaryController::class, 'show']);
        Route::get('/places/autocomplete', [PlaceController::class, 'autocomplete']);
        Route::get('/places/details', [PlaceController::class, 'details']);
        Route::get('/places/static-map', [PlaceController::class, 'staticMap']);
        Route::get('/dashboard-changes', [DashboardChangeController::class, 'index']);
        Route::post('/issue-reports', [IssueReportController::class, 'store']);
        Route::post('/push-notification-tokens', [PushNotificationDeviceTokenController::class, 'store']);
        Route::delete('/push-notification-tokens', [PushNotificationDeviceTokenController::class, 'destroy']);
        Route::get('/google-calendar/status', [GoogleCalendarController::class, 'status']);
        Route::post('/google-calendar/auth-url', [GoogleCalendarController::class, 'authUrl']);
        Route::post('/google-calendar/sync', [GoogleCalendarController::class, 'sync']);
        Route::patch('/google-calendar/calendars', [GoogleCalendarController::class, 'calendars']);
        Route::delete('/google-calendar', [GoogleCalendarController::class, 'disconnect']);
        Route::get('/outlook-calendar/status', [OutlookCalendarController::class, 'status']);
        Route::post('/outlook-calendar/auth-url', [OutlookCalendarController::class, 'authUrl']);
        Route::post('/outlook-calendar/sync', [OutlookCalendarController::class, 'sync']);
        Route::patch('/outlook-calendar/calendars', [OutlookCalendarController::class, 'calendars']);
        Route::delete('/outlook-calendar', [OutlookCalendarController::class, 'disconnect']);
        Route::get('/external-calendars/providers', [ExternalCalendarController::class, 'providers']);
        Route::post('/external-calendars/import', [ExternalCalendarController::class, 'import']);
        Route::post('/apple-calendar/import', [AppleCalendarController::class, 'import']);

        Route::get('/note-folders', [DomainResourceController::class, 'listNoteFolders']);
        Route::post('/note-folders', [DomainResourceController::class, 'storeNoteFolder']);
        Route::patch('/note-folders/{noteFolder}', [DomainResourceController::class, 'updateNoteFolder']);
        Route::delete('/note-folders/{noteFolder}', [DomainResourceController::class, 'destroyNoteFolder']);
        Route::get('/notes', [DomainResourceController::class, 'listNotes']);
        Route::post('/notes', [DomainResourceController::class, 'storeNote']);
        Route::patch('/notes/{note}', [DomainResourceController::class, 'updateNote']);
        Route::delete('/notes/{note}', [DomainResourceController::class, 'destroyNote']);
        Route::get('/tasks', [DomainResourceController::class, 'listTasks']);
        Route::get('/tasks/past', [DomainResourceController::class, 'listPastTasks']);
        Route::post('/tasks', [DomainResourceController::class, 'storeTask']);
        Route::patch('/tasks/{task}', [DomainResourceController::class, 'updateTask']);
        Route::delete('/tasks/{task}', [DomainResourceController::class, 'destroyTask']);
        Route::get('/reminders', [DomainResourceController::class, 'listReminders']);
        Route::post('/reminders', [DomainResourceController::class, 'storeReminder']);
        Route::patch('/reminders/{reminder}', [DomainResourceController::class, 'updateReminder']);
        Route::delete('/reminders/{reminder}', [DomainResourceController::class, 'destroyReminder']);
        Route::get('/calendar-events', [DomainResourceController::class, 'listCalendarEvents']);
        Route::post('/calendar-events', [DomainResourceController::class, 'storeCalendarEvent']);
        Route::patch('/calendar-events/{calendarEvent}', [DomainResourceController::class, 'updateCalendarEvent']);
        Route::delete('/calendar-events/{calendarEvent}', [DomainResourceController::class, 'destroyCalendarEvent']);
        Route::get('/event-categories', [DomainResourceController::class, 'listEventCategories']);
        Route::post('/event-categories', [DomainResourceController::class, 'storeEventCategory']);
        Route::patch('/event-categories/{eventCategory}', [DomainResourceController::class, 'updateEventCategory']);
        Route::delete('/event-categories/{eventCategory}', [DomainResourceController::class, 'destroyEventCategory']);
        Route::middleware('admin')->prefix('admin')->group(function (): void {
            Route::get('/dashboard/summary', [AdminDashboardController::class, 'summary']);
            Route::get('/issue-reports/summary', [IssueReportController::class, 'summary']);
            Route::get('/plan-limits', [AdminPlanLimitController::class, 'show']);
            Route::patch('/plan-limits/plans', [AdminPlanLimitController::class, 'updatePlans']);
            Route::post('/plan-limits/enterprise-customers', [AdminPlanLimitController::class, 'storeEnterpriseCustomer']);
            Route::patch('/plan-limits/enterprise-customers/{enterpriseCustomerLimit}', [AdminPlanLimitController::class, 'updateEnterpriseCustomer']);
            Route::delete('/plan-limits/enterprise-customers/{enterpriseCustomerLimit}', [AdminPlanLimitController::class, 'destroyEnterpriseCustomer']);
            Route::get('/coupon-codes', [CouponCodeController::class, 'index']);
            Route::post('/coupon-codes', [CouponCodeController::class, 'store']);
            Route::delete('/coupon-codes/{couponCode}', [CouponCodeController::class, 'destroy']);
            Route::patch('/issue-reports/{issueReport}', [IssueReportController::class, 'update']);
        });
    });
});
