<?php

use App\Http\Controllers\Api\ActivityEventController;
use App\Http\Controllers\Api\AdminCommandRunController;
use App\Http\Controllers\Api\AdminHermesController;
use App\Http\Controllers\Api\AdminLiveLookupController;
use App\Http\Controllers\Api\AdminPlanLimitController;
use App\Http\Controllers\Api\AdminSettingsController;
use App\Http\Controllers\Api\AdminUsageController;
use App\Http\Controllers\Api\AssistantRunController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BillingController;
use App\Http\Controllers\Api\ConversationMessageController;
use App\Http\Controllers\Api\ConversationSessionController;
use App\Http\Controllers\Api\DashboardChangeController;
use App\Http\Controllers\Api\DomainResourceController;
use App\Http\Controllers\Api\GoogleCalendarController;
use App\Http\Controllers\Api\IssueReportController;
use App\Http\Controllers\Api\OutlookCalendarController;
use App\Http\Controllers\Api\PushNotificationDeviceTokenController;
use App\Http\Controllers\Api\QuickVoiceReplyController;
use App\Http\Controllers\Api\RealtimeSessionController;
use App\Http\Controllers\Api\TextToSpeechController;
use App\Http\Controllers\Api\TodaySummaryController;
use App\Http\Controllers\Api\WorkspaceController;
use Illuminate\Support\Facades\Route;

Route::middleware('api.rate_limit')->group(function (): void {
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/email-availability', [AuthController::class, 'emailAvailability']);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::get('/google-calendar/callback', [GoogleCalendarController::class, 'callback']);
    Route::get('/outlook-calendar/callback', [OutlookCalendarController::class, 'callback']);
    Route::post('/billing/stripe/webhook', [BillingController::class, 'webhook']);

    Route::middleware('auth.bearer')->group(function (): void {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::patch('/auth/me', [AuthController::class, 'update']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::delete('/account', [AuthController::class, 'destroy']);
        Route::get('/account/export', [AuthController::class, 'export']);
        Route::get('/billing/subscription', [BillingController::class, 'show']);
        Route::post('/billing/mobile-subscriptions/setup', [BillingController::class, 'mobileSubscriptionSetup']);
        Route::post('/billing/mobile-subscriptions/confirm', [BillingController::class, 'confirmMobileSubscription']);
        Route::get('/billing/payment-method', [BillingController::class, 'paymentMethod']);
        Route::post('/billing/payment-method/setup', [BillingController::class, 'paymentMethodSetup']);
        Route::post('/billing/payment-method/checkout-session', [BillingController::class, 'paymentMethodCheckoutSession']);
        Route::post('/billing/payment-method/confirm', [BillingController::class, 'confirmPaymentMethod']);
        Route::post('/billing/checkout-sessions', [BillingController::class, 'checkoutSession']);
        Route::post('/billing/subscription/upgrade', [BillingController::class, 'upgrade']);
        Route::post('/billing/subscription/change-plan', [BillingController::class, 'changePlan']);
        Route::post('/billing/subscription/cancel', [BillingController::class, 'cancel']);
        Route::post('/billing/subscription/resume', [BillingController::class, 'resume']);

        Route::get('/workspaces', [WorkspaceController::class, 'index']);
        Route::post('/workspaces', [WorkspaceController::class, 'store']);
        Route::patch('/workspaces/default', [WorkspaceController::class, 'setDefault']);
        Route::get('/workspaces/{workspace}', [WorkspaceController::class, 'show']);
        Route::patch('/workspaces/{workspace}', [WorkspaceController::class, 'update']);
        Route::post('/workspaces/{workspace}/invitations', [WorkspaceController::class, 'invite']);
        Route::post('/workspace-invitations/{token}/accept', [WorkspaceController::class, 'accept']);
        Route::patch('/workspaces/{workspace}/members/{member}', [WorkspaceController::class, 'updateMember']);
        Route::delete('/workspaces/{workspace}/members/{member}', [WorkspaceController::class, 'destroyMember']);
        Route::post('/workspaces/{workspace}/leave', [WorkspaceController::class, 'leave']);
        Route::post('/workspaces/{source}/sync-all', [WorkspaceController::class, 'syncAll']);
        Route::patch('/workspaces/{workspace}/google-calendars', [WorkspaceController::class, 'calendars']);

        Route::get('/assistant/sessions', [ConversationSessionController::class, 'index']);
        Route::post('/assistant/sessions', [ConversationSessionController::class, 'store']);
        Route::get('/assistant/sessions/{session}', [ConversationSessionController::class, 'show']);
        Route::post('/assistant/sessions/{session}/cancel', [ConversationSessionController::class, 'cancel']);
        Route::post('/assistant/sessions/{session}/messages', [ConversationMessageController::class, 'store']);
        Route::post('/assistant/sessions/{session}/messages/{message}/branch', [ConversationMessageController::class, 'branch']);
        Route::post('/assistant/sessions/{session}/runs', [AssistantRunController::class, 'store']);
        Route::get('/assistant/sessions/{session}/events', [ActivityEventController::class, 'index']);
        Route::get('/assistant/runs/{run}', [AssistantRunController::class, 'show']);
        Route::post('/assistant/runs/{run}/cancel', [AssistantRunController::class, 'cancel']);
        Route::post('/assistant/realtime/sessions', [RealtimeSessionController::class, 'store']);
        Route::post('/assistant/realtime/calls', [RealtimeSessionController::class, 'call']);
        Route::post('/assistant/realtime/tool-calls', [RealtimeSessionController::class, 'toolCall']);
        Route::post('/assistant/realtime/messages', [RealtimeSessionController::class, 'message']);
        Route::post('/assistant/realtime/usage', [RealtimeSessionController::class, 'usage']);
        Route::post('/assistant/realtime/client-events', [RealtimeSessionController::class, 'clientEvent']);
        Route::get('/assistant/realtime/dashboard-context', [RealtimeSessionController::class, 'dashboardContext']);
        Route::post('/ai/realtime/session', [RealtimeSessionController::class, 'store']);
        Route::post('/assistant/voice/quick-reply', [QuickVoiceReplyController::class, 'store']);
        Route::post('/assistant/tts', [TextToSpeechController::class, 'store']);

        Route::get('/today', [TodaySummaryController::class, 'show']);
        Route::get('/dashboard-changes', [DashboardChangeController::class, 'index']);
        Route::post('/issue-reports', [IssueReportController::class, 'store']);
        Route::post('/push-notification-tokens', [PushNotificationDeviceTokenController::class, 'store']);
        Route::delete('/push-notification-tokens', [PushNotificationDeviceTokenController::class, 'destroy']);
        Route::get('/google-calendar/status', [GoogleCalendarController::class, 'status']);
        Route::post('/google-calendar/auth-url', [GoogleCalendarController::class, 'authUrl']);
        Route::post('/google-calendar/sync', [GoogleCalendarController::class, 'sync']);
        Route::patch('/google-calendar/calendars', [GoogleCalendarController::class, 'calendars']);
        Route::delete('/google-calendar', [GoogleCalendarController::class, 'disconnect']);
        Route::get('/outlook-calendar/status', [OutlookCalendarController::class, 'status']);
        Route::post('/outlook-calendar/auth-url', [OutlookCalendarController::class, 'authUrl']);
        Route::post('/outlook-calendar/sync', [OutlookCalendarController::class, 'sync']);
        Route::patch('/outlook-calendar/calendars', [OutlookCalendarController::class, 'calendars']);
        Route::delete('/outlook-calendar', [OutlookCalendarController::class, 'disconnect']);

        Route::get('/memory-items', [DomainResourceController::class, 'listMemoryItems']);
        Route::post('/memory-items', [DomainResourceController::class, 'storeMemoryItem']);
        Route::patch('/memory-items/{memoryItem}', [DomainResourceController::class, 'updateMemoryItem']);
        Route::delete('/memory-items/{memoryItem}', [DomainResourceController::class, 'destroyMemoryItem']);
        Route::get('/memory-summaries', [DomainResourceController::class, 'listMemorySummaries']);
        Route::get('/memory/request-history', [DomainResourceController::class, 'requestHistory']);
        Route::get('/memory/activity-timeline', [DomainResourceController::class, 'activityTimeline']);
        Route::get('/note-folders', [DomainResourceController::class, 'listNoteFolders']);
        Route::post('/note-folders', [DomainResourceController::class, 'storeNoteFolder']);
        Route::patch('/note-folders/{noteFolder}', [DomainResourceController::class, 'updateNoteFolder']);
        Route::delete('/note-folders/{noteFolder}', [DomainResourceController::class, 'destroyNoteFolder']);
        Route::get('/notes', [DomainResourceController::class, 'listNotes']);
        Route::post('/notes', [DomainResourceController::class, 'storeNote']);
        Route::patch('/notes/{note}', [DomainResourceController::class, 'updateNote']);
        Route::delete('/notes/{note}', [DomainResourceController::class, 'destroyNote']);
        Route::get('/tasks', [DomainResourceController::class, 'listTasks']);
        Route::get('/tasks/past', [DomainResourceController::class, 'listPastTasks']);
        Route::post('/tasks', [DomainResourceController::class, 'storeTask']);
        Route::patch('/tasks/{task}', [DomainResourceController::class, 'updateTask']);
        Route::delete('/tasks/{task}', [DomainResourceController::class, 'destroyTask']);
        Route::get('/reminders', [DomainResourceController::class, 'listReminders']);
        Route::post('/reminders', [DomainResourceController::class, 'storeReminder']);
        Route::patch('/reminders/{reminder}', [DomainResourceController::class, 'updateReminder']);
        Route::delete('/reminders/{reminder}', [DomainResourceController::class, 'destroyReminder']);
        Route::get('/calendar-events', [DomainResourceController::class, 'listCalendarEvents']);
        Route::post('/calendar-events', [DomainResourceController::class, 'storeCalendarEvent']);
        Route::patch('/calendar-events/{calendarEvent}', [DomainResourceController::class, 'updateCalendarEvent']);
        Route::delete('/calendar-events/{calendarEvent}', [DomainResourceController::class, 'destroyCalendarEvent']);
        Route::get('/event-categories', [DomainResourceController::class, 'listEventCategories']);
        Route::post('/event-categories', [DomainResourceController::class, 'storeEventCategory']);
        Route::patch('/event-categories/{eventCategory}', [DomainResourceController::class, 'updateEventCategory']);
        Route::delete('/event-categories/{eventCategory}', [DomainResourceController::class, 'destroyEventCategory']);
        Route::get('/approvals', [DomainResourceController::class, 'listApprovals']);
        Route::post('/approvals', [DomainResourceController::class, 'storeApproval']);
        Route::patch('/approvals/{approval}', [DomainResourceController::class, 'updateApproval']);
        Route::delete('/approvals/{approval}', [DomainResourceController::class, 'destroyApproval']);
        Route::post('/approvals/{approval}/approve', [DomainResourceController::class, 'approveApproval']);
        Route::post('/approvals/{approval}/deny', [DomainResourceController::class, 'denyApproval']);
        Route::get('/blockers', [DomainResourceController::class, 'listBlockers']);
        Route::post('/blockers', [DomainResourceController::class, 'storeBlocker']);
        Route::patch('/blockers/{blocker}', [DomainResourceController::class, 'updateBlocker']);
        Route::delete('/blockers/{blocker}', [DomainResourceController::class, 'destroyBlocker']);

        Route::middleware('admin')->prefix('admin')->group(function (): void {
            Route::get('/settings', [AdminSettingsController::class, 'show']);
            Route::get('/settings/models', [AdminSettingsController::class, 'models']);
            Route::patch('/settings', [AdminSettingsController::class, 'update']);
            Route::get('/plan-limits', [AdminPlanLimitController::class, 'show']);
            Route::patch('/plan-limits/plans', [AdminPlanLimitController::class, 'updatePlans']);
            Route::post('/plan-limits/enterprise-customers', [AdminPlanLimitController::class, 'storeEnterpriseCustomer']);
            Route::patch('/plan-limits/enterprise-customers/{enterpriseCustomerLimit}', [AdminPlanLimitController::class, 'updateEnterpriseCustomer']);
            Route::delete('/plan-limits/enterprise-customers/{enterpriseCustomerLimit}', [AdminPlanLimitController::class, 'destroyEnterpriseCustomer']);
            Route::get('/hermes/status', [AdminHermesController::class, 'show']);
            Route::post('/hermes/update', [AdminHermesController::class, 'update']);
            Route::get('/live-lookup/providers', [AdminLiveLookupController::class, 'index']);
            Route::get('/command-runs/{commandRun}', [AdminCommandRunController::class, 'show']);
            Route::get('/usage/summary', [AdminUsageController::class, 'summary']);
            Route::get('/usage/logs', [AdminUsageController::class, 'logs']);
            Route::get('/usage/alerts', [AdminUsageController::class, 'alerts']);
            Route::patch('/issue-reports/{issueReport}', [IssueReportController::class, 'update']);
        });
    });
});
