import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:audioplayers/audioplayers.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:flutter_stripe/flutter_stripe.dart' as stripe;
import 'package:geocoding/geocoding.dart';
import 'package:geolocator/geolocator.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:speech_to_text/speech_recognition_error.dart' as speech_error;
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:url_launcher/url_launcher.dart';

import 'bean_realtime_conversation.dart';
import 'firebase_options.dart';
import 'hermes_api_client.dart';

part 'src/core/runtime_services.dart';
part 'src/app/hermes_bean_app.dart';
part 'src/theme/hey_bean_theme.dart';
part 'src/dashboard/dashboard_models.dart';
part 'src/shell/command_center_shell.dart';
part 'src/widgets/create_item_menu.dart';
part 'src/billing/signup_paywall.dart';
part 'src/onboarding/agent_onboarding.dart';
part 'src/onboarding/guided_onboarding.dart';
part 'src/auth/signed_out.dart';
part 'src/shell/command_center_content.dart';
part 'src/home/command_center_home.dart';
part 'src/chat/hero_chat.dart';
part 'src/chat/approvals_and_messages.dart';
part 'src/today/today_home_view.dart';
part 'src/calendar/event_detail.dart';
part 'src/calendar/calendar_helpers.dart';
part 'src/calendar/month_agenda.dart';
part 'src/calendar/title_time_editor.dart';
part 'src/tasks/task_reminder_views.dart';
part 'src/memory/memory_view.dart';
part 'src/notes/notes_view.dart';
part 'src/settings/settings_view.dart';
part 'src/items/item_tiles.dart';
part 'src/helpers/collection_and_format_helpers.dart';
part 'src/account/account_widgets.dart';
part 'src/widgets/form_widgets.dart';
part 'src/widgets/banners_and_tour.dart';
part 'src/navigation/bottom_menu.dart';
