-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPp5FUcUdubLvfz7b
Y/nNwmXdpe/rtqY5bfSfzoC45LWgCgYIKoZIzj0DAQehRANCAARCwoc2btOU7G/E
WNiwpltYEZNhiTBgtYqv3FhG5UGKIPMknLnbyWNinkH7FA/UAdh1QLwQ3ovT5dnc
rIlvRI20
-----END PRIVATE KEY-----